### ISSUE TITLE
Pot of Coals issues

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Assets#95]
- The outer folder name should be `PotOfCoals`, not `glTFPotOfCoals`.
- There should not be two different GLB files.  One will suffice.
- There should not be a folder named `glTF-Animation`.

via https://github.com/KhronosGroup/glTF-Sample-Assets/pull/90#issuecomment-1879143470

**Comment by echadwick-artist** [comment]
I can rename the folder and files to match.

The asset has a non-animated version because it was built for use with the [Khronos glTF Viewer](https://www.khronos.org/blog/khronos-releases-open-source-ios-app-for-viewing-gltf-files) which doesn't support KHR_animation_pointer.

Subsequently I made an animated version, and thought since it looked great (and we need more animation-pointer examples) perhaps we should add it to the repo. But I'm OK with removing it if needed.

**Comment by echadwick-artist** [comment]
@emackey Should I make a new folder for the animated version of PotOfCoals?

**Comment by emackey** [comment]
> Should I make a new folder for the animated version of PotOfCoals?

Yes, I think so.  The organizational structure here still has a limitation inherited from the predecessor repository, where it doesn't make any clear allowance for several similar copies of almost the same model with various modifications applied.  Often a set of variations of a model are not particularly appealing or understandable to users, but as we see here, there can be technical reasons why one user would want a different variation from another.  Given the current folder structure, I think we can only present these as two separate models, such as PotOfCoals and PotOfCoalsAnimated, or similar.

Suggestions welcome.

**Comment by echadwick-artist** [comment]
Submitting animated asset via PR #127
